# Generated by Django 5.2 on 2025-04-05 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='featured_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_images'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
