# Generated by Django 5.2.1 on 2025-05-23 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_blogpage_author_blogpage_featured_by_blogpage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255, null=True)),
                ("image", models.ImageField(null=True, upload_to="blog_images")),
                ("content", models.TextField(null=True)),
                ("author", models.CharField(max_length=255, null=True)),
                ("category", models.CharField(max_length=255, null=True)),
                ("tags", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("featured_by", models.CharField(max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="BlogPage",
        ),
    ]
