# Generated by Django 5.2.1 on 2025-05-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogposts_delete_blogpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPosts',
            new_name='BlogPost',
        ),
    ]
