# Generated by Django 5.2.1 on 2025-05-27 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("blogs", "0007_alter_blogpost_author"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPost",
            new_name="Blog",
        ),
    ]
