# Generated by Django 5.2.1 on 2025-05-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("blogs", "0008_rename_blogpost_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blog_author",
                to="accounts.usermodel",
            ),
        ),
    ]
